<!-- Generated by ai-rules-sync 1.2.6 from ai-rules@2.7.0 -->
<!-- Do not edit directly. Run `ai-rules sync` to update. -->
<!-- To customise, edit normally; changes are preserved via three-way merge. -->
---
applies-to:
    - node
    - nodejs
    - express
    - fastify
    - nestjs
    - koa
baseline: Node.js >= 20 (LTS), TypeScript >= 5.1 (strict mode)
conventions: RFC-2119 (MUST / SHOULD / MAY)
description: Node.js architectural patterns, SOLID principles, and engineering standards for production-grade services. Framework-agnostic.
name: node-rules
owners:
    - backend-platform-team
replaces:
    - node-express-rules
tier: 2
version: 1.2.0
---
# Node.js Engineering Rules

> Rule severity follows RFC 2119. **MUST** rules block merges; **SHOULD** rules require a documented exception in the PR.
> Baseline: Node.js 20 LTS. New services MUST use TypeScript with `strict: true`.

## Project Setup & TypeScript

- New services MUST be written in TypeScript with `strict: true`. JavaScript-only services are forbidden in new projects.
- Use ESM (`"type": "module"`) for new projects. CommonJS MAY be retained in existing services with a documented migration path.
- Lockfiles MUST be committed. CI MUST install with frozen lockfiles (`npm ci`, `pnpm install --frozen-lockfile`). Pin exact versions in applications; use compatible ranges only in libraries.
- A single package manager MUST be used per repo. Do not mix `npm`, `pnpm`, and `yarn` invocations.

## Layered Architecture & Portability

- Business logic MUST be independent of web frameworks (Express, Fastify, NestJS). Framework-specific code lives only in the transport layer.
- Enforce strict flow: Transport (Routes/Gateways) → Application (Controllers/Handlers) → Domain (Services/Logic) → Infrastructure (Repositories/Adapters). No layer may skip a layer below it or depend on a layer above it.
- Use API specifications (OpenAPI, GraphQL schema) as the single source of truth. Generate or validate scaffolds against API contracts.
- Group modules by domain feature. Minimize dependencies between features to isolate changes.

## Dependency Inversion & Infrastructure

- Prioritize Node.js built-in modules (`fs`, `path`, `crypto`) over external dependencies.
- External clients (DB, cache, APIs) MUST be injected into services via constructors or factories.
- Services MUST depend on interfaces or abstractions, not concrete implementations.
- Modules MUST NOT read `process.env` directly. Use a centralized configuration provider that validates environment variables at startup with a schema.

## Async Patterns & Performance

- Blocking synchronous I/O and CPU-intensive tasks MUST NOT run on the event loop. Offload to Worker Threads or background queues.
- Use `async/await` exclusively. Do not mix Promise chains and callbacks.
- Set explicit timeouts for all outbound network calls.
- Implement circuit breakers for all outbound network calls.
- Use profiling tools to identify memory leaks and event loop delays during development.

## Graceful Shutdown

- Every service MUST handle `SIGTERM` and `SIGINT` by: stopping new request acceptance, draining in-flight requests, closing DB and cache connections, then exiting with code `0`.
- Shutdown MUST complete within a configurable deadline (default 10 s); force-exit with code `1` after the deadline expires.
- Register shutdown handlers in the application lifespan — not scattered across modules.

## Error Handling & Observability

- Use a hierarchy of typed errors (`DomainError`, `InfrastructureError`, `ValidationError`). A framework-agnostic global error handler MUST translate errors into structured responses.
- Catch `uncaughtException` and `unhandledRejection` at the process level. Log error context and exit gracefully on unhandled exceptions.
- Inject a unique correlation ID at the request entry point. Propagate it through all logs and downstream calls via a standard header (`x-correlation-id` or equivalent).
- All log output MUST be structured JSON with at minimum: `timestamp`, `level`, `message`, `correlationId`, and `service`. `console.log` is forbidden in production paths.
- Expose `/health` (liveness — process is alive) and `/readyz` (readiness — dependencies reachable) on every service. Health endpoints MUST NOT require authentication.

## Security & Boundary Defense

- Sanitize and validate all external input at the system boundary using an allow-list schema. Treat all data from the transport layer as untrusted.
- Use parameterized queries or type-safe ORMs/Query Builders. String concatenation for database queries is forbidden.
- Rate limiting MUST be applied to all public-facing endpoints. Apply at the reverse proxy or CDN layer; supplement with application-level limiting for per-user quotas.
- Set security response headers (`Content-Security-Policy`, `X-Content-Type-Options`, `Referrer-Policy`, `Strict-Transport-Security`) via middleware or proxy. Do not rely solely on hosting-platform defaults.
- Scan dependencies regularly for vulnerabilities and license compliance. High/critical CVEs MUST be triaged within one business day.
- Run the process with the minimum necessary permissions. Never hardcode credentials. Rotate all secrets on a defined schedule.

## Engineering Standards

- Use Conventional Commits to automate versioning and changelogs.
- Maintain high unit test coverage for domain logic. Use integration tests for infrastructure boundaries. Never mock the database in repository tests.
- Keep documentation co-located with implementation. Maintain `SKILL.md` or modular instructions for complex workflows.