<!-- Generated by ai-rules-sync 1.2.6 from ai-rules@2.7.0 -->
<!-- Do not edit directly. Run `ai-rules sync` to update. -->
<!-- To customise, edit normally; changes are preserved via three-way merge. -->
---
applies-to: all
description: Core coding standards and architecture patterns applied to every project regardless of stack. Always loaded.
name: core-rules
owners:
    - ai-governance-council
tier: 1
version: 3.1.1
---
# Core Rules

## Code Quality

- Write code for the next reader, not the next compiler — clarity over cleverness.
- One function, one responsibility. If you need "and" to describe what it does, split it.
- Prefer flat over nested. Early returns, guard clauses, and simple conditions reduce cognitive load.
- Delete dead code immediately; version control is the safety net.
- Avoid magic numbers and strings — name every constant that isn't self-evident.
- Keep functions short enough to fit on one screen without scrolling.
- Consistent naming beats clever naming; follow the existing conventions of the codebase.

## Testing

- Write tests before or alongside code, never as an afterthought.
- Each test must verify one behavior and have a descriptive name that reads as a specification.
- Tests must be deterministic — no reliance on system time, random values, or execution order.
- Prefer integration tests over unit tests for behavior that crosses system boundaries.
- Do not mock internal code; only mock at the boundary of external systems.
- A failing test suite blocks all merges, no exceptions.
- Aim for coverage of behaviors, not coverage of lines.

## Security

- Treat all external input as untrusted; validate and sanitize at every entry point.
- Never hardcode secrets, credentials, or keys — use environment variables or a secrets manager.
- Apply the principle of least privilege to services, roles, and API keys.
- Sanitize all output rendered to users to prevent injection attacks.
- Keep dependencies up to date; automate vulnerability scanning in CI.
- Log security-relevant events (auth failures, permission denials) but never log credentials or PII.
- Default to deny; explicitly grant permissions rather than explicitly denying them.

## Error Handling

- Handle errors at the layer that has enough context to act on them; propagate upward otherwise.
- Never silently swallow exceptions — log or surface every failure.
- Distinguish between recoverable errors (retry, fallback) and unrecoverable ones (fail fast).
- Return structured error types, not raw strings, so callers can act programmatically.
- Provide actionable error messages: what failed, why, and what to do next.

## Version Control

- Each commit represents one logical change; never bundle unrelated modifications.
- Write commit messages in imperative mood: "Add X", "Fix Y", "Remove Z".
- The commit body explains *why*, not what — the diff already shows what changed.
- Branch from the main branch; keep branches short-lived (days, not weeks).
- Never force-push to a shared branch without team consensus.
- All changes enter the main branch via a reviewed pull request.

## Documentation

- Document the *why* and the *constraints*, not the *what* — code explains itself.
- Keep documentation co-located with code so it stays current.
- README must cover: purpose, local setup, and how to run tests.
- Mark all public APIs with intent and contract; omit implementation details.
- Delete documentation that is no longer accurate; stale docs are worse than none.

## Dependencies

- Add a dependency only when the benefit clearly outweighs the maintenance cost.
- Pin exact versions in application code; use compatible ranges only in library code.
- Audit new dependencies for security posture, license, and maintenance activity.
- Remove unused dependencies before merging.
- Isolate third-party integrations behind an abstraction layer so they can be swapped.

## Configuration & Environments

- Separate configuration from code; the same binary must run in every environment.
- Define a single source of truth for configuration schema with validation on startup.
- Provide safe defaults — the system should start and degrade gracefully without optional config.
- Never commit environment-specific values; use templated examples (`.env.example`).

## Observability

- Emit structured logs (key-value or JSON) for machine parseability.
- Log at the right level: DEBUG for development detail, INFO for operational events, ERROR for failures requiring attention.
- Every external call must be traceable — include correlation IDs across service boundaries.
- Expose health-check and readiness endpoints for all long-running services.
- Define and track SLIs before a service goes to production.

## Performance

- Measure before optimizing; never guess at bottlenecks.
- Cache at the layer closest to the consumer, but define clear invalidation rules.
- Paginate or stream large result sets; never return unbounded collections.
- Avoid N+1 query patterns by fetching related data in bulk.
- Set timeouts on every network call and external dependency.

## Code Review

- Review for correctness, security, and maintainability — not style (automate style).
- Approve only code you understand well enough to maintain yourself.
- Comments must be specific and actionable; avoid vague feedback.
- Authors address or explicitly defer every review comment before merging.
- Reviewer is a collaborator, not a gatekeeper — suggest, don't dictate.

## Analysis Before Implementation

- For any bug fix, refactor, new feature, performance improvement, dependency change, or config schema change, share an RCA brief before writing code. When multiple approaches have meaningfully different trade-offs, present ranked options with a recommendation; otherwise commit to one.
- The brief must state: the root cause (mechanism, not symptom), the proposed approach (what changes and what does not), every file that will be modified or created, and risks or trade-offs.
- Approval is explicit ("yes", "go ahead", "looks good", "implement it") or implicit (the user re-states the same request after reading the brief). Silence, follow-up questions, and option-selection refinement ("what about X?") are not approval to implement.
- For single-file, self-evident changes, a one-sentence statement of intent and rationale satisfies the brief requirement.
- Does not apply to typo fixes, trivial renames, formatting, or doc-only changes.
- Do not implement first and explain after. Do not list hypotheses without committing to one. Do not use vague scope ("several files") — enumerate exactly which files.

---

# Architecture Patterns

## Separation of Concerns

- Divide systems into layers with clear responsibilities: presentation, business logic, data access.
- No layer may skip a layer below it or depend on a layer above it.
- Business logic must not leak into the presentation or persistence layer.

## Domain-Driven Design (DDD) Essentials

- Model software around the business domain, using the same language as domain experts (ubiquitous language).
- Group code by domain concepts (bounded contexts), not technical roles (controllers/services/repos).
- Protect domain invariants inside aggregates; only the aggregate root exposes mutation.
- Use domain events to communicate state changes across bounded contexts.

## Hexagonal Architecture (Ports & Adapters)

- The core domain has zero knowledge of infrastructure — databases, queues, HTTP frameworks.
- Define ports (interfaces) in the domain; implement adapters in the infrastructure layer.
- Swap any adapter (e.g., database, message broker) without touching business logic.
- All dependencies point inward toward the domain, never outward.

## Service Design

- Design services around business capabilities, not data entities.
- Each service owns its data store; no direct cross-service database access.
- Communicate synchronously (REST/gRPC) for queries that need immediate response; asynchronously (events/queues) for state changes.
- Services must be independently deployable and independently scalable.
- Design for failure: every service-to-service call may fail and must degrade gracefully.

## API Design

- APIs are contracts; treat breaking changes with the same gravity as data migrations.
- Version APIs from day one (`/v1/…`); never break an existing published version.
- Use consistent resource naming, status codes, and error envelope formats across all endpoints.
- Validate request payloads at the API boundary, not deep in business logic.
- Design APIs around intent (what the caller wants to accomplish), not around internal data models.

## Event-Driven Architecture

- Prefer events for cross-bounded-context communication to keep services decoupled.
- Events are immutable facts in the past tense: `OrderPlaced`, `PaymentFailed`.
- Design consumers to be idempotent — the same event may be delivered more than once.
- Store events before publishing (outbox pattern) to prevent lost messages on failure.
- Define and version event schemas explicitly; treat schema changes as breaking changes.

## Data Management

- Each service is the single authoritative source for its domain data.
- Denormalize read models (CQRS read side) rather than writing complex queries against the write model.
- Prefer append-only event logs over mutable state where auditability matters.
- Apply database migrations as versioned, forward-only scripts; never edit a committed migration.
- Plan for eventual consistency in distributed systems; document where it applies.

## Resilience Patterns

- Apply circuit breakers around all remote calls to prevent cascade failures.
- Use retries with exponential back-off and jitter; set a maximum retry budget.
- Implement bulkheads to isolate failures — a slow dependency must not exhaust shared resources.
- Prefer timeouts over waiting indefinitely; fail fast and let the caller decide how to recover.
- Test failure modes in lower environments (chaos engineering) before they hit production.

## Security Architecture

- Authenticate at the entry point of every service; never trust a caller because of network position.
- Issue short-lived tokens; rotate credentials automatically.
- Encrypt data at rest and in transit; treat plaintext storage of sensitive data as a bug.
- Isolate sensitive workloads in separate services or execution environments.
- Apply defense in depth — no single control should be the only safeguard.

## Scalability & Deployment

- Design services to be stateless; persist all shared state in external stores.
- Make deployments incremental: feature flags, blue-green, or canary releases over big-bang cut-overs.
- Automate all environment provisioning; no snowflake servers.
- Store all infrastructure definitions as code under version control.
- Build once, deploy everywhere — the same artifact must move through every environment unchanged.