# AI Rules

<!-- Generated by ai-rules-sync. Do not edit directly. -->

## Core rules

<!-- tier: 1 — always applied -->

- [core-rules](.claude/core-rules.md) — Core coding standards and architecture patterns applied to every project regardless of stack. Always loaded.

## Stack rules

<!-- tier: 2 — applied when stack matches -->

- [jamstack-rules](.claude/jamstack-rules.md) (jamstack, nextjs, gatsby, hugo, eleventy, serverless, edge) — Jamstack architecture principles, decoupling, and performance-first web standards.
- [nextjs-rules](.claude/nextjs-rules.md) (nextjs, react, jamstack) — Next.js App Router architecture, rendering strategies, and production engineering standards.
- [node-rules](.claude/node-rules.md) (node, nodejs, express, fastify, nestjs, koa) — Node.js architectural patterns, SOLID principles, and engineering standards for production-grade services. Framework-agnostic.
- [react-rules](.claude/react-rules.md) (react, nextjs) — React architecture and SOLID principles for production-grade component systems. Loaded for React and Next.js projects.
- [tailwind-css-rules](.claude/tailwind-css-rules.md) (tailwindcss, react, nextjs, jamstack) — Tailwind CSS utility-first conventions, design token governance, and scalable styling standards.

