<!-- Generated by ai-rules-sync 1.2.6 from ai-rules@2.7.0 -->
<!-- Do not edit directly. Run `ai-rules sync` to update. -->
<!-- To customise, edit normally; changes are preserved via three-way merge. -->
---
applies-to:
    - jamstack
    - nextjs
    - gatsby
    - hugo
    - eleventy
    - serverless
    - edge
conventions: RFC-2119 (MUST / SHOULD / MAY)
description: Jamstack architecture principles, decoupling, and performance-first web standards.
name: jamstack-rules
owners:
    - frontend-platform-team
tier: 2
version: 2.0.1
---
# Jamstack Engineering Rules

> Rule severity follows RFC 2119. **MUST** rules block merges; **SHOULD** rules require a documented exception in the PR; **MAY** rules are recommendations.

## Decoupling & Architecture

- The frontend MUST be decoupled from backend services and communicate only via versioned, documented APIs (REST with explicit `/api/v{n}` paths, or GraphQL with schema versioning/deprecation policy).
- The frontend MUST NOT depend on raw upstream API response shapes. Access every external service (CMS, search, auth) through a typed data-access layer owned by the frontend team. This is the swap-ability boundary.
- Prerendering (SSG) MUST be the default for non-personalized content. ISR / on-demand revalidation SHOULD be used to update content without full rebuilds; full-site rebuild-on-publish MAY be used only for small sites (< ~500 pages).
- Services MUST be API-first: no service may expose functionality only through its UI.
- Managed services SHOULD be preferred for Auth, CMS, Search, and email over self-built equivalents, unless data-residency or cost constraints are documented.

## Performance & Delivery

- The frontend MUST be deployed to a global CDN with immutable, atomic deployments — a deploy is either fully live or not live; no partially updated state may ever be served.
- Instant rollback MUST be possible via CDN pointer switching to a previous immutable deploy. Rollback MUST NOT require a rebuild.
- HTML-first delivery MUST be prioritized: meaningful content renders without JavaScript wherever feasible; client-side JS is minimized and lazy-loaded when non-critical.
- Cache headers MUST be explicit. `Cache-Control` for HTML documents and for hashed static assets MUST be set deliberately (typically short/`no-cache` + revalidation for HTML, `immutable, max-age=31536000` for content-hashed assets). Never rely on CDN defaults.

## Serverless & Dynamic Logic

- Dynamic server-side logic MUST live in serverless/regional functions or origin services, not in the static layer.
- The frontend MUST be stateless. Persistent user state lives in remote databases accessed via API; session state lives in `HttpOnly`, `Secure`, `SameSite` cookies. Authentication tokens, refresh tokens, session identifiers, and capability tokens MUST NOT be stored in `localStorage` or `sessionStorage` — any value readable by JavaScript on the page is exposed to XSS.
- Personalization that affects above-the-fold content SHOULD run at the edge or be isolated behind streaming boundaries so it does not force the whole page dynamic.

## Edge Functions & Request Interception

- Distinguish three tiers and use the cheapest one that works:
  1. **Edge functions** (Cloudflare Workers, Vercel Edge runtime, Deno Deploy) — restricted V8 isolates, no Node.js built-ins, limited CPU, no file system.
  2. **Node-runtime request interception** (e.g., Next.js 16 `proxy.ts`) — full Node runtime at the framework's network boundary.
  3. **Regional serverless functions / origin services** — for database access and heavy computation.
- Edge functions MUST be used exclusively for latency-sensitive, stateless operations: token *validation* (not issuance), request rewriting, A/B routing, geolocation redirects.
- Edge functions MUST NOT perform database queries, secret fetching beyond platform-injected env vars, or heavy computation. Offload to tier 2 or 3.
- Request-interception layers (any tier) MUST NOT be the sole authorization mechanism. Authorization MUST be re-verified at the data-access point (route handler, server action, or service). This is a hard rule: CVE-2025-29927 demonstrated a complete middleware auth bypass in a major framework via a spoofed internal header.
- Treat every edge/interception boundary as a network boundary: validate and sanitize data passed downstream as you would external input.
- Edge code MUST be tested in a local edge-runtime emulator (`wrangler dev`, `vercel dev`) before deployment; Node-based unit tests alone are insufficient because runtime APIs differ.

## Environment & Secrets

- Build-time variables (baked into the artifact and every cached copy) MUST be separated from runtime variables (injected at request time). Changing a build-time variable requires a rebuild — plan accordingly.
- Secrets, API keys, and credentials MUST NEVER appear in build-time or client-exposed variables. Anything reachable by client JavaScript is public.
- Client-safe variables MUST carry the platform prefix (`NEXT_PUBLIC_`, `VITE_`, `GATSBY_`). All unprefixed variables are server-only by definition and MUST never be referenced in client bundles (enforce with a lint rule or `server-only` package where available).
- Secrets MUST live in a dedicated secrets store (Vault, AWS Secrets Manager, Doppler, or platform-equivalent). `.env` files MUST be git-ignored; commit only `.env.example` with placeholder values.
- Environment variables MUST be validated at startup/build with a schema (e.g., Zod via `@t3-oss/env`). A missing or malformed variable fails the build, not the first request.
- API keys and tokens MUST be rotated on a defined schedule and immediately on suspected exposure. Provision the new key before invalidating the old one to avoid availability gaps.

## Core Web Vitals & Performance Budgets

- LCP, CLS, and INP MUST be measured on every release using RUM and/or synthetic testing (Lighthouse CI, WebPageTest). Local profiling alone does not count.
- Performance budgets MUST be enforced in CI: LCP ≤ 2.5 s on a throttled 4G profile, CLS ≤ 0.1, INP ≤ 200 ms. Deployments that regress beyond budget thresholds MUST be blocked.
- CWV regressions MUST be attributed to their source before shipping; the usual suspects are third-party scripts, unoptimized images, render-blocking resources, and main-thread JS. INP above 200 ms signals main-thread work must be deferred, chunked, or moved off-thread.
- A client JS bundle budget SHOULD be defined per route (suggested ceiling: 200 KB compressed first-load JS for content pages) and tracked in CI.

## Third-Party Scripts & Supply Chain

- Non-critical third-party scripts MUST load with `defer`/`async` or a framework loader (e.g., `next/script` with appropriate strategy). Synchronous third-party scripts in `<head>` are forbidden.
- Subresource Integrity (`integrity`) hashes MUST be applied to third-party scripts on external CDNs whose content is version-pinned. For scripts that self-update (analytics snippets), proxy the script through an origin you control, or obtain an explicit exception approved in the PR. An approved exception requires: `script-src` restricted to the exact script origin (no wildcards), nonce- or hash-based CSP directives (not a plain origin allow-list), and the script included in the quarterly third-party audit.
- `Content-Security-Policy` MUST enumerate third-party origins explicitly. Wildcards in `script-src` nullify CSP and are forbidden. Prefer nonce- or hash-based CSP over origin allow-lists where the framework supports it.
- Third-party scripts MUST be audited quarterly; remove scripts whose owning service is no longer used.
- Dependency supply chain: lockfiles MUST be committed and CI MUST install with frozen lockfiles (`npm ci`, `pnpm install --frozen-lockfile`). New dependencies SHOULD pass an automated review (license, known CVEs, install scripts) before merge. High/critical vulnerability alerts MUST be triaged within one business day.

## Engineering Standards

- Every commit MUST trigger an automated build and a preview environment.
- Preview checks MUST validate: type-check, lint, unit tests, Core Web Vitals budget, accessibility (axe-core or equivalent — WCAG 2.2 AA target), and broken links, before merge.
- Image compression, modern formats (AVIF/WebP), CSS minification, and font subsetting/optimization MUST be automated in the pipeline, never manual.
- Security headers MUST be set explicitly: `Content-Security-Policy`, `Strict-Transport-Security`, `X-Content-Type-Options`, `Referrer-Policy`, and either CSP `frame-ancestors` or `X-Frame-Options`. Do not rely solely on hosting-platform defaults.
- Token handling MUST be enforced at the system boundary: validate, never log, and never forward tokens to third parties.
- Browser support targets SHOULD be expressed via Baseline (e.g., "Baseline Widely Available") rather than ad-hoc browser lists.